version: "3.8"

services:
  jupyterhub:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JUPYTERHUB_VERSION: latest
    image: jupyterhub
    container_name: jupyterhub
    networks:
      - jupyterhub-network
      - webproxy
    # ports:
    #   - "8080:8000"
    expose:
      - "8000"
    volumes:
      # these are needed to allow users to loggin with the
      # same credentials on the host server
      - "/home:/home"
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
      - "/etc/shadow:/etc/shadow:ro"
      # these are for configuration
      - "./config/jupyterhub:/srv/jupyterhub"
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "jupyterhub-data:/data"
    environment:
      # This username will be a JupyterHub admin
      JUPYTERHUB_ADMIN: admin
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub-network
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: jupyter/datascience-notebook:python-3.11
      # for the proxy to detect the container
      VIRTUAL_HOST: recherche-bouassi-1
      VIRTUAL_PORT: 8000
      VIRTUAL_PATH: /jupyter/
    restart: always

volumes:
  jupyterhub-data:


networks:
  jupyterhub-network:
    name: jupyterhub-network
  webproxy:
    external: true
