version: "3.8"

services:
  jupyterhub:
    build:
      context: .
      dockerfile: Dockerfile.hub
      args:
        JUPYTERHUB_VERSION: latest
    image: jupyterhub
    container_name: jupyterhub
    networks:
      - jupyterhub-network
      - webproxy
    # ports:
    #   - "8080:8000"
    expose:
      - "8000"
    volumes:
      # these are needed to allow users to loggin with the
      # same credentials on the host server
      - "/home:/home"
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
      - "/etc/shadow:/etc/shadow:ro"
      # these are for configuration
      - "./config/jupyterhub:/srv/jupyterhub"
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "jupyterhub-data:/data"
    environment:
      # This username will be a JupyterHub admin
      JUPYTERHUB_ADMIN: ${JUPYTERHUB_ADMIN}
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub-network
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: jupyter-datascience-matlab
      # for the proxy to detect the container
      VIRTUAL_HOST: ${HOSTNAME}
      VIRTUAL_PORT: 8000
      VIRTUAL_PATH: /jupyter/
    restart: always

  # run "docker compose build jupyter-notebook" before starting the hub
  jupyter-notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
      args:
        LICENSE_SERVER: ${LICENSE_SERVER}
        MATLAB_RELEASE: ${MATLAB_RELEASE}
        # add one toolbox name per line
        MATLAB_PRODUCT_LIST: >
          MATLAB Deep_Learning_Toolbox
          Signal_Processing_Toolbox
          Statistics_and_Machine_Learning_Toolbox
          Parallel_Computing_Toolbox
        BASE_JUPYTER_IMAGE: quay.io/jupyter/datascience-notebook:latest
    image: jupyter-datascience-matlab:latest
    profiles:
      # this prevents docker compose up from starting this service
      - build

volumes:
  jupyterhub-data:


networks:
  jupyterhub-network:
    # set the name so it is not prefixed
    name: jupyterhub-network
  webproxy:
    external: true
